server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8080/eureka
  instance:
    hostname: eureka-server
  server:
    renewal-threshold-update-interval-ms: 60000
    use-read-only-response-cache: false
    response-cache-auto-expiration-in-seconds: 0
